import React, { Fragment } from "react";
import { Link } from "react-router-dom";
import { Container } from "reactstrap";
import { companyName, siteName, contactEmail } from "../utils/constants";

const EULA = () => (
  <Container className="mb-5">
    <Fragment>
      <div>
        <h1>EULA</h1>
        <p class="subtitle">Legal</p>
        <h1 class="title">End User License Agreement</h1>
        <p class="content">{companyName} ("{siteName}"), AND EACH OF ITS AFFILIATES AND SUBSIDIARIES (COLLECTIVELY, "{siteName}") IS WILLING TO LICENSE THE SOFTWARE (defined below) TO YOU ONLY UPON THE CONDITION THAT YOU ACCEPT ALL OF THE TERMS CONTAINED IN THIS END USER LICENSE AGREEMENT ("EULA"). THIS EULA IS A LEGAL AGREEMENT BETWEEN YOU AND {siteName}. READ IT CAREFULLY BEFORE COMPLETING THE INSTALLATION PROCESS AND/OR USING THE SOFTWARE. BY USING THE SOFTWARE YOU ACKNOWLEDGE THAT YOU HAVE READ THE TERMS OF THE EULA AND AGREE TO THEM. IF YOU ARE AGREEING TO THESE TERMS ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE LEGAL AUTHORITY TO BIND THE LEGAL ENTITY TO THESE TERMS. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT WISH TO BE BOUND BY THE TERMS, THEN YOU CANNOT USE THE SOFTWARE IDENTIFIED BELOW OR ANY OTHER MEDIA ON WHICH THE SOFTWARE IS CONTAINED.
          <ol class="">
            <li>DEFINITIONS.
              <ol type="a">
                <li>Software. Software is defined as {siteName}’s platforms and APIs, including but not limited to {siteName} Platform, {siteName} WebSockets, as well as any other software, updates or error corrections provided by {siteName}, and any associated data, media, files, user manuals, programming guides, signals, messages, alerts and other documentation provided to you by {siteName} or otherwise disseminated by {siteName}.</li>
                <li>License. License is defined as a limited, revocable, non-sublicensable, non-exclusive, non-transferable right to use Software, granted to you.</li>
              </ol>
            </li>
            <li>GRANT OF LICENSE. {siteName} grants you the right to install, use, access, display and run the Software on any computer or mobile device, where applicable, that you own or control, for personal, non-commercial use, unless you and {siteName} have agreed otherwise in writing, and provided that you comply with all terms and conditions of this EULA.</li>
            <li>SCOPE AND LIMITATIONS. You may not rent, lease, lend, sell, redistribute, reuse, retransmit, sublicense or exploit the Software including the Software data, text, graphics, video, audio, codes, user interface design or logs without explicit written permission and agreement between you and {siteName}. You may not copy (except as expressly permitted by this EULA), decompile, reverse engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Software, any updates, or any part thereof including but not limited to the Software data, text, graphics, video, audio, codes, user interface design or logs. Any attempt to do so is a violation of the rights of {siteName}. The terms of the EULA will govern any upgrades provided by {siteName} that replace and/or supplement the original Software, unless such upgrade is accompanied by a separate license in which case the terms of that license will govern. ANY AND ALL DATA PROVIDED BY {siteName} IS STRICTLY FOR DISPLAY USE ONLY, UNLESS OTHERWISE CLEARLY STATED IN SUBSEQUENT PRODUCT AGREEMENTS. USE OF THE DATA IN ANY OTHER FORM OR MANNER IS A VIOLATION OF THIS EULA. {siteName} WILL REPORT UNLAWFUL USAGE OF PROPRIETARY DATA PRODUCTS TO THE RESPECTFUL EXCHANGE(S) AND/OR DATA PROVIDERS ALONG WITH ALL INFORMATION ON SUCH ACCOUNT. The Software is not intended for distribution to, or use by, any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation. It is your responsibility to ascertain the terms of the EULA and comply with any local law or regulation to which you are subject. You shall not use or permit anyone to use the Software for any unlawful or unauthorized purpose. The information provided to you in the Software is the exclusive proprietary content of {siteName} and where applicable, its third party vendors, licensors and the affiliates thereof. Nothing in this EULA shall provide you with any proprietary rights in the Software or any information provided to you in the Software.</li>
            <li>RISKS. As a condition to this License you understand and agree that your access and/or use of the Software will expose you to risks associated with the access and/or use of software that may not be compatible with your computer equipment. You hereby agree to accept such risks, including, but not limited to, failure of or damage to, hardware, software, communication lines or systems, and/or other computer equipment. {siteName} expressly denies any liability with respect to the foregoing, and you agree to fully indemnify, defend and hold harmless {siteName} from any and all damages, liabilities, losses, costs and expenses that may arise therefrom.</li>
            <li>CONSENT TO USE OF DATA. You agree that {siteName} may collect and use technical data and related information, including but not limited to technical information about your computer, system and application software, and peripherals, that is gathered periodically to facilitate the provision of Software updates, product support and other services to you (if any) related to this EULA.</li>
            <li>LINKS TO THIRD PARTY CONTENT. You may link to third party content through the use of the Software. The third party sites are not under the control of {siteName} and {siteName} is not responsible for the contents of any third party sites, any links contained in third party sites, or any changes or updates to third party sites. Inclusion of any link does not imply an endorsement by {siteName} of the third party site. Certain third-party information transmitted in the Software may require additional approvals by the vendor or third party that supplies such information. You are responsible for making an application to and receiving such written approval by the required third-party and paying any fees or charges where applicable.</li>
            <li>TERMINATION. The License granted to you under this EULA can be terminated by {siteName} at any time without notice, with or without cause. {siteName} reserves the right to terminate your rights under this License without notice from {siteName} if you fail to comply with any term(s) of this EULA. Upon termination of the License, you shall cease all use of the Software, and destroy all copies, full or partial, of the Software. You acknowledge that certain information is being supplied by third parties with whom {siteName} has entered into an agreement. In the event any agreement between a third party provider of information or software and {siteName} is terminated, {siteName} will stop providing you with this information or software immediately and without notice. Pursuant to the terms of Section 10, neither {siteName} nor any third party vendor or information provider with whom {siteName} has entered into an agreement shall have any liability to you in connection with such termination.</li>
            <li>INTELLECTUAL PROPERTY. You acknowledge that the Software is protected by copyright and other intellectual property laws. You further acknowledge that all right, title and interest therein are the sole property of {siteName} and its third party licensors, where applicable, and that you receive no rights, title or interests in the Software except as expressly set forth herein. You agree not to challenge either {siteName}’s or any third party licensor's rights in or otherwise attempt to assert any rights in the Software, except those provided under this EULA.</li>
            <li>NO WARRANTY: {siteName} DOES NOT MAKE ANY EXPRESS OR IMPLIED WARRANTIES ABOUT THE SOFTWARE, INCLUDING BUT NOT LIMITED TO; IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. THE SOFTWARE IS MADE AVAILABLE TO YOU "AS IS" AND "AS AVAILABLE" AND {siteName} DOES NOT WARRANT THAT ANY DEFECTS OR INACCURACIES WILL BE CORRECTED. {siteName} DOES NOT WARRANT THAT THE SOFTWARE WILL MEET YOUR NEEDS, OR THAT YOUR USE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE. {siteName} ALSO MAKES NO WARRANTY THAT THE RESULTS OBTAINED FROM THE USE OF THE SOFTWARE WILL BE ACCURATE OR RELIABLE, OR THAT THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL RELATED TO THE SOFTWARE WILL MEET YOUR EXPECTATIONS. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY {siteName} OR ITS AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY. {siteName} AND ITS THIRD PARTY CONTENT PROVIDERS, THIRD PARTY LICENSORS AND ANY AFFILIATES THEREOF DO NOT MAKE ANY EXPRESS OR IMPLIED WARRANTIES REGARDING THE ACCURACY OR TIMELINESS OF ANY AND ALL INFORMATION PROVIDED VIA THE SOFTWARE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU.</li>
            <li>LIMITATION OF LIABILITY: TO THE EXTENT PERMISSIBLE BY LAW, IN NO EVENT SHALL {siteName}, ANY THIRD PARTY CONTENT PROVIDER, ANY THIRD PARTY LICENSOR OR ANY AFFILIATES THEREOF BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES ("LOSSES"), ARISING OUT OF OR RELATED TO YOUR USE OR INABILITY TO USE THE SOFTWARE, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT OR OTHERWISE) AND EVEN IF {siteName}, ANY THIRD PARTY CONTENT PROVIDER, ANY THIRD PARTY LICENSOR OR ANY AFFILIATES THEREOF HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. FURTHERMORE, EXCEPT AS OTHERWISE REQUIRED BY LAW, {siteName} WILL NOT BE LIABLE TO YOU OR ANYONE ELSE FOR ANY LOSS RESULTING FROM A CAUSE OVER WHICH SUCH {siteName} DOES NOT HAVE DIRECT CONTROL. THIS INCLUDES FAILURE OF ELECTRONIC OR MECHANICAL EQUIPMENT OR COMMUNICATIONS LINES (INCLUDING TELEPHONE, CABLE AND INTERNET), UNAUTHORIZED ACCESS, VIRUSES, THEFT, OPERATOR ERRORS, SEVERE OR EXTRAORDINARY WEATHER (INCLUDING FLOOD, EARTHQUAKE, OR OTHER ACT OF GOD), FIRE, WAR, INSURRECTION, TERRORIST ACT, RIOT, LABOR DISPUTE AND OTHER LABOR PROBLEMS, ACCIDENT, EMERGENCY OR ACTION OF GOVERNMENT. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. USE OF ANY THIRD-PARTY SOFTWARE WILL BE GOVERNED BY THE APPLICABLE LICENSE AGREEMENT, IF ANY, WITH SUCH THIRD PARTY. {siteName} IS NOT RESPONSIBLE FOR ANY THIRD-PARTY SOFTWARE AND WILL HAVE NO LIABILITY OF ANY KIND FOR LOSSES RESULTING FROM YOUR USE OF SUCH THIRD-PARTY SOFTWARE WITH {siteName}'S SOFTWARE. {siteName} MAKES NO WARRANTY OF ANY KIND WITH RESPECT TO SUCH THIRD-PARTY SOFTWARE.</li>
            <li>GOVERNING LAWS AND JURISDICTION. Unless otherwise agreed, this EULA and it's enforcement is governed by the laws of the state of Georgia, without regard to principles of conflicts of law, and shall inure to the benefit of {siteName}'s successors and assigns, whether by merger, consolidation, or otherwise. This is the case regardless of whether you reside or transact business with {siteName} in Georgia or elsewhere. Unless a dispute would be governed by an applicable arbitration clause, you irrevocably agree to submit to the jurisdiction of the federal and state courts located within the city and county of Cobb, GA and hereby waive any objection to the convenience or propriety of venue therein. Provided however, that nothing herein shall prevent {siteName} from bringing any action in the courts of any other jurisdiction. If for any reason a court of competent jurisdiction finds any provision, or portion thereof, to be unenforceable, the remainder of this License shall continue in full force and effect.</li>
            <li>GOVERNING LANGUAGE. Any translation of this License is done for local requirements or for your convenience. In the event of a dispute between the English and any non-English versions, the English version of this License shall govern, to the extent not prohibited by local law in your jurisdiction.</li>
            <li>MODIFICATIONS TO THE EULA. {siteName} reserves the right to change the terms and conditions of the EULA at any time with or without notice by posting such changes on the https://{siteName}.io website. You are responsible for regularly reviewing these terms and conditions for any modifications and agree to be bound by the same.</li>
          </ol>
          <p>If you have any questions on {siteName}.io Inc's User Agreement, you can contact us at {contactEmail}</p>
        </p>
      </div>
    </Fragment>
  </Container>
);

export default EULA;
