import React, { Fragment } from "react";
import { Container } from "reactstrap";
import { siteName, siteUrl, companyName, contactEmail } from "../utils/constants";

const Privacy = () => {
  return (  
  <Container className="mb-5">
    <Fragment>
      <div>
      <p class="subtitle">Legal</p>
      <h1 class="title">Privacy Policy</h1>
      <p class="content">READ THIS PRIVACY POLICY CAREFULLY BEFORE USING OR OBTAINING ANY MATERIALS, INFORMATION, PRODUCTS OR SERVICES THROUGH THIS SITE.</p>
      <p class="content">{siteName}, Inc. is a Delaware corporation operating under the name {siteName} (“{siteName}” the “Company,” "{companyName}", “we,” “us,” “our”). The Company takes your privacy seriously. The Company pledges to follow the provisions of this Privacy Policy in order to protect your privacy rights. This Privacy Policy forms part of the {siteName} Terms of Service and is incorporated by reference therein.</p>
      <p class="content">This Privacy Policy (“Policy”) outlines our general policy and practices for protecting your private information on the {siteUrl} website and related services (collectively, the “Site”). It includes the types of information we gather, how we use it, and the choices individuals have regarding our use of their information. This Policy applies to all personal information received by us whether in electronic, written, or verbal format. Personal information is information that can be associated with a specific person and used to identify that person. Personal information does not include information that has been anonymized so that it does not identify a specific individual, which may be used for any legal purpose.</p>
      <p class="content">The Company reserves the right to modify this Policy at any time and will do so from time to time. Each modification shall be effective upon its posting to the Site. Your continued use of the Site following any such modification constitutes your acceptance of any changes to this Policy. It is therefore important that you review this Policy regularly. If you have any questions concerning this Policy please contact the Company at {contactEmail}</p>
      <p class="content">
        <ol>
          <li>Scope
            <p class="content">This Policy covers all of the Site. However, it does not apply to entities that the Company does not own or control including advertisers or developers of content. The Company may include third-party links on the Site. These third-party sites are governed by their own privacy policies and not this Policy. We therefore have no responsibility or liability for the content and activities of these third-party sites. Please check the privacy policy of any third-party site you interact with on or off the Site.</p>
          </li>
          <li>Information Company Collects About You
            <p class="content">Each time a user accesses the Site they receive a “cookie” from us. We use cookies (small pieces of data stored for an extended period of time on a computer, mobile phone, or other device) to make the Site easier to use, and to protect both you and the Company. These cookies give the Company information about your use of the Site. You may remove or block cookies using the settings in your browser, but doing so may impact your ability to use the Site. We may also use pixels, widgets and other tools to gather such information to improve the experience of the website or mobile application.</p>
            <p class="content">We may contract with third-party service providers to assist us in better understanding our site visitors. These service providers are not permitted to use the information collected on our behalf except to help us conduct and improve our business.</p>
            <p class="content">When you access the Site from a computer, mobile phone, or other device, we may collect information from that device about your browser type, location, and IP address, as well as the pages you visit and the date and time you access the Site.</p>
            <p class="content">We may keep track of some of the actions you take on the Site including the user profiles and the analyses you upload. We may also ask you about your personal and investing habits. Even if you do not provide this information, we may obtain it from messages you post, your profile, or the analyses you post, and the analyses you view or purchase. We may retain the details of connections or transactions you make on the Site.</p>
            <p class="content">We may collect information on your use of the site, such as pages visited, links clicked, text entered, and mouse movements, as well as information more commonly collected such as the referring URL, browser, operating system, and IP address. We use publicly available sources to approximate your geographic region and Internet Service Provider based on your IP address. We also collect information on your usage of our APIs and Services. We collect information that may be personally identifiable, such as IP addresses. Also, you may choose to interact with the Site in a way that results in your providing Personal Information to us, such as giving us your name and email address when signing up for a free trial of the Services or creating an account to license the Services we provide.</p>
            <p class="content">We may collect information from the ads you view when you use the Site. We may also keep track of links you click on in emails you receive from us. This is done to increase the relevancy of the ads you see.</p>
            <p class="content">We may also gather information about you from the content other Users post on the Site. Some of this information may contain personal information.</p>
          </li>
          <li>Information You Provide to Company
            <p class="content">As part of the process to become a user of {siteName}, we require you to provide your username, email address, and a password. You may voluntarily provide other information including, but not limited to, mailing address, phone number, place of employment, past employment and education history, etc.</p>
            <p class="content">While using the Site you may provide text, files, images, photos, videos, location data, or any other materials (collectively “User Content” or “Content”) to the Company by uploading, posting, or publishing the User Content on the Site. User Content you place on the Site may contain a picture of your face.</p>
            <p class="content">We may retain the details of connections or transactions you make on the Site.</p>
            <p class="content">Use of the Site may include you posting Content. Some of this Content is placed in a public forum. Any information in a public forum is accessible by anyone, including people who are not users of the Site. Please keep this in mind when posting Content on the Site.</p>
          </li>
          <li>Information You Provide to Other Users
            <p class="content">You may also interact directly with other Users of the Site. When you interact with others on the Site you may provide other personal information about yourself such as political or topical views, religious affiliation, or marital status. Please use care when disclosing private information to other Users of the Site. Be aware they may share information you give them with other Users you may not know. They may also share the information outside the Site without your prior approval. We do not have control over the actions of our Users, and accept no responsibility or liability for their actions. We do not require Users to undergo a screening process and make no representations or warranties as to the truthfulness of information Users provide. Please keep this fact in mind when using the Site.</p>
          </li>
          <li>How We Use Your Personal Information
            <p class="content">We use the information you are required to provide to become a user in order to insure you are over the age of eighteen (18). The Site is not meant to be used by anyone under the age of eighteen. If you are under eighteen, please do not attempt to register for {siteName} or send us any personal information. If you believe someone has submitted information from someone under eighteen, contact us and we will remove the information as soon as possible.</p>
            <p class="content">We may share non-personally identifying information we collect from your activity on the Site with other users, news agencies and other third parties in order for them to better understand investment trends and patterns specific to {siteName} Users.</p>
            <p class="content">We will use the information we collect to provide services and features to you. We will also use the information to measure and improve the Site, and to provide you with customer support.</p>
            <p class="content">We may contact you with service-related announcements from time to time. We may also update you about new product offerings and communications relevant to your use of the Site. We may include Content in the emails we send to you. You may opt-out of certain communications by signing into your account and changing your communication preferences. You can also remove yourself from communication by clicking on an “unsubscribe” hyperlink contained in every communication.</p>
            <p class="content">We may use information about you that we collect from other Users to supplement information in your account. This includes activities like linking your account to a post placed by another User which references Content placed you. We may allow other Users to use the contact information they have about you, such as your username, to find you.</p>
            <p class="content">Certain software applications and applets transmit data to us. We may not make a formal disclosure if we believe our collection of and use of the information is the obvious purpose of the Site or its related application. If it is not obvious that we are collecting or using such information, the first time you provide the information we will disclose that we are collecting it from you.</p>
            <p class="content">We may use the information we collect to prevent potential illegal activities. We also use a variety of methods to detect and address anomalous activity and screen content to prevent abuse.</p>
          </li>
          <li>How We Share Your Information
            <p class="content">The Company may share your information with third-parties when we believe doing so is permitted by you, reasonably necessary to offer our services, or when legally required to do so. We will not share your information with third-parties in a way we think violates your privacy. The following are examples of ways we may share your information, however, this list is informative not exhaustive.</p>
            <p class="content">Certain information you provide to us will be shared by using our search function. This allows other Users to locate your profile and User Content, and it allows new users to find people they know on the Site. We provide some public information to search engines. This information allows search engines to locate the Site. It also allows people to locate you on the Site using a major search engine. This does not mean all information you post on the Site may be accessed using a search engine. From time-to-time {siteName} may offer contests to Users of the Site. All contests offered by {siteName} will be governed by the {siteName} Terms of Use and this Policy and may be governed by additional terms. Contests may be sponsored by third-party organizations and the Company may share information you submit as part of the contest to sponsors. Any information that you choose to submit as part of a Contest submission may be disclosed to third-party sponsors and other individuals as set out in the Contest terms. We may also share information when we have a good faith belief it is necessary to prevent fraud or other illegal activity, to prevent imminent bodily harm, or to protect you and ourselves from a third-party violation of the Terms of Service of the Site. This may include sharing information with other companies, lawyers, and courts or other government entities. We may disclose information pursuant to subpoenas, court orders, or other requests (including criminal and civil matters) if we have a good faith belief that the response is required by law. This may include requests from jurisdictions outside of the United States if the Company has a good faith belief that the response is required under the local law in that jurisdiction, is applicable to users from that jurisdiction, and is consistent with generally accepted international standards. Company may disclose analyzed data in the form of purchasing trends or statistical data. No personally identifiable attributes will be attached to this disclosure.</p>
          </li>
          <li>Business or Asset Transfer or Sale
            <p class="content">The Company may be sold, sell or buy businesses or assets of businesses, or merge with another business. In such transactions, personal information generally is one of the transferred business assets. Also, in the event that the Company, a line of business of the Company, or substantially all of our assets are transferred, personal information may be one of the transferred assets. If any such change in ownership or control of your personal information will take place, we will make a reasonable effort to provide notice on the Site and via your most recently provided email address.</p>
          </li>
          <li>Security
            <p class="content">Company shall only process personal information in a way that is compatible with and relevant to the purpose for which it was collected or has been authorized. To the extent necessary for those purposes, Company shall take reasonable steps to ensure that personal information is accurate, complete, current, and reliable for its intended use.</p>
          </li>
          <li>Data Integrity
            <p class="content">The Company reserves the right to modify this Policy at any time and will do so from time to time. Each modification shall be effective upon its posting to the Site. Your continued use of the Site following any such modification constitutes your acceptance of any changes to this Policy. It is therefore important that you review this Policy regularly. If you have any questions concerning this Policy please contact the Company at {contactEmail}</p>
          </li>
          <li>Access
            <p class="content">You can review, update, and change some of your personal information – including your email address and password – in your profile at any time. We will allow you access to your personal information and allow you to correct, amend, or delete inaccurate information. For access requests please contact {contactEmail}. Access will not be allowed where the burden or expense of providing access would be disproportionate to the risks to your privacy or where personal rights other than your own would be violated.</p>
          </li>
          <li>"Do Not Track" Disclosures
            <p class="content">Certain state laws require us to indicate whether we honor “Do Not Track” settings in your browser concerning targeted advertising. We adhere to the standards set out in this Privacy Policy and do not monitor or follow any Do Not Track browser requests.</p>
          </li>
          <li>Children's Policy
            <p class="content">The Children’s Online Privacy Protection Act was created to protect children under the age of 13 from unsuspecting acts or practices in conjunction with collecting, using, and disclosing any information about them. Our Site is not intended for anyone under the age of 13. If you are under 13, do not use or provide any information on or through our Site. If we learn we have collected or received personal information from a child under 13 without verification of parental consent, we will delete that information. If you are a parent or guardian or otherwise believe we might have any information from or about a child under 13, please contact us so that we can delete the child's information. The Site will never knowingly accept, collect, maintain or use any information from a child under the age of 13. If a child whom we know to be under the age of 13 sends personal information to us online, we will only use that information to respond directly to that child or notify parents.</p>
          </li>
          <li>Data Protection Principles
            <p class="content">The Company is committed to processing data in accordance with its responsibilities under the GDPR. Article 5 of the GDPR requires that personal data shall be (i) processed lawfully, fairly and in a transparent manner in relation to individuals; (ii) collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; further processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall not be considered to be incompatible with the initial purposes; (iii) adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed; (iv) accurate and, where necessary, kept up to date; every reasonable step must be taken to ensure that personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay; (v) kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes subject to implementation of the appropriate technical and organisational measures required by the GDPR in order to safeguard the rights and freedoms of individuals; and (vi) processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures.”</p>
          </li>
          <li>Other
            <p class="content">By using the Site, you consent to having your personal information and data transferred to and processed in the United States. Please contact us with any questions or concerns regarding our policy at this address: {contactEmail}.</p>
          </li>
        </ol>
      </p>    
      </div>
    </Fragment>
  </Container>
  );
}

export default Privacy;
